services:
  anime:
    build: ./anime
    ports:
      - "4000:4000"
    volumes:
      - ./anime/data:/app/data
    environment:
      - TEST_CRUD=False
      - SQLITE=False
      - DATABASE_URL=sqlite:////app/data/sql_app.db
